useful research links :

- RpcExceptions are not logged : https://github.com/nestjs/nest/issues/303
- since RpcExeptions are not instances of HttpExceptions, a Internal Server Input is always thrown (doc of Exceptions Filters).
- kinda map observable into promise : https://stackoverflow.com/questions/71327273/issue-returning-values-with-rxjs-and-nestjs
